const TRIVIA_QUESTIONS = [
  // General Knowledge
  { question: "What is the capital of France?", answer: "Paris", category: "General Knowledge" },
  { question: "Which planet is known as the Red Planet?", answer: "Mars", category: "General Knowledge" },
  { question: "What is the largest ocean on Earth?", answer: "Pacific", category: "General Knowledge" },
  { question: "How many colors are there in a rainbow?", answer: "Seven", category: "General Knowledge" },
  { question: "What is the name of the fairy in Peter Pan?", answer: "Tinkerbell", category: "General Knowledge" },
  { question: "Which animal is known as the King of the Jungle?", answer: "Lion", category: "General Knowledge" },
  { question: "What is the standard currency of the United Kingdom?", answer: "Pound", category: "General Knowledge" },
  { question: "Which country is home to the Kangaroo?", answer: "Australia", category: "General Knowledge" },
  { question: "What is the hardest natural substance on Earth?", answer: "Diamond", category: "General Knowledge" },
  { question: "How many days are in a leap year?", answer: "366", category: "General Knowledge" },
  { question: "What is the primary language spoken in Brazil?", answer: "Portuguese", category: "General Knowledge" },
  { question: "What element does a diamond consist of?", answer: "Carbon", category: "General Knowledge" },
  { question: "What color is a school bus in the US?", answer: "Yellow", category: "General Knowledge" },
  { question: "How many legs does a spider have?", answer: "Eight", category: "General Knowledge" },
  { question: "What is the capital city of Japan?", answer: "Tokyo", category: "General Knowledge" },

  // Science & Tech
  { question: "What is the chemical symbol for Gold?", answer: "Au", category: "Science & Tech" },
  { question: "What is the closest star to Earth?", answer: "Sun", category: "Science & Tech" },
  { question: "What gas do plants absorb from the atmosphere for photosynthesis?", answer: "Carbon Dioxide", category: "Science & Tech" },
  { question: "What is the power house of the cell?", answer: "Mitochondria", category: "Science & Tech" },
  { question: "Who is credited with inventing the World Wide Web?", answer: "Tim Berners-Lee", category: "Science & Tech" },
  { question: "What is the chemical formula for water?", answer: "H2O", category: "Science & Tech" },
  { question: "Which planet is closest to the Sun?", answer: "Mercury", category: "Science & Tech" },
  { question: "What is the speed of sound in a vacuum (in meters per second)?", answer: "Zero", category: "Science & Tech" },
  { question: "What programming language is named after a type of snake?", answer: "Python", category: "Science & Tech" },
  { question: "What does CPU stand for?", answer: "Central Processing Unit", category: "Science & Tech" },
  { question: "What is the atomic number of Hydrogen?", answer: "1", category: "Science & Tech" },
  { question: "Which organ in the human body consumes the most energy?", answer: "Brain", category: "Science & Tech" },
  { question: "What is the unit of electrical resistance?", answer: "Ohm", category: "Science & Tech" },
  { question: "Which planet has the most moons?", answer: "Saturn", category: "Science & Tech" },
  { question: "What is the main gas found in the air we breathe?", answer: "Nitrogen", category: "Science & Tech" },

  // History & Geography
  { question: "Who was the first President of the United States?", answer: "George Washington", category: "History & Geography" },
  { question: "What is the longest river in the world?", answer: "Nile", category: "History & Geography" },
  { question: "In which country would you find the Great Pyramid of Giza?", answer: "Egypt", category: "History & Geography" },
  { question: "Which year did World War II end?", answer: "1945", category: "History & Geography" },
  { question: "What is the smallest country in the world?", answer: "Vatican City", category: "History & Geography" },
  { question: "Who was the first person to step on the Moon?", answer: "Neil Armstrong", category: "History & Geography" },
  { question: "Which civilization built the Machu Picchu in Peru?", answer: "Inca", category: "History & Geography" },
  { question: "What is the capital of Australia?", answer: "Canberra", category: "History & Geography" },
  { question: "Which empire was ruled by Julius Caesar?", answer: "Roman Empire", category: "History & Geography" },
  { question: "Which country is also known as the Land of the Rising Sun?", answer: "Japan", category: "History & Geography" },
  { question: "What is the largest country by land area?", answer: "Russia", category: "History & Geography" },
  { question: "Which explorer is credited with discovering America in 1492?", answer: "Christopher Columbus", category: "History & Geography" },
  { question: "What was the previous name of Istanbul?", answer: "Constantinople", category: "History & Geography" },
  { question: "Which mountain is the tallest in the world?", answer: "Mount Everest", category: "History & Geography" },
  { question: "Which canal connects the Atlantic and Pacific Oceans?", answer: "Panama Canal", category: "History & Geography" },

  // Pop Culture & Movies
  { question: "Which movie won the first Academy Award for Best Picture?", answer: "Wings", category: "Pop Culture & Movies" },
  { question: "Who played Jack Dawson in the movie Titanic?", answer: "Leonardo DiCaprio", category: "Pop Culture & Movies" },
  { question: "What is the name of the fictional wizarding school in Harry Potter?", answer: "Hogwarts", category: "Pop Culture & Movies" },
  { question: "Which band sang the hit song 'Bohemian Rhapsody'?", answer: "Queen", category: "Pop Culture & Movies" },
  { question: "Who is the creator of the Star Wars franchise?", answer: "George Lucas", category: "Pop Culture & Movies" },
  { question: "Which actress played Katniss Everdeen in The Hunger Games?", answer: "Jennifer Lawrence", category: "Pop Culture & Movies" },
  { question: "What is the highest-grossing film of all time (unadjusted for inflation)?", answer: "Avatar", category: "Pop Culture & Movies" },
  { question: "Which pop singer is known as the 'King of Pop'?", answer: "Michael Jackson", category: "Pop Culture & Movies" },
  { question: "What is the name of Simba's father in The Lion King?", answer: "Mufasa", category: "Pop Culture & Movies" },
  { question: "Which superhero is also known as Bruce Wayne?", answer: "Batman", category: "Pop Culture & Movies" },
  { question: "What is the name of the coffee shop in the TV show Friends?", answer: "Central Perk", category: "Pop Culture & Movies" },
  { question: "Which singer released the album 'Midnights' in 2022?", answer: "Taylor Swift", category: "Pop Culture & Movies" },
  { question: "Who directed the movie 'Interstellar' and 'Inception'?", answer: "Christopher Nolan", category: "Pop Culture & Movies" },
  { question: "What is the name of the toy cowboy in Toy Story?", answer: "Woody", category: "Pop Culture & Movies" },
  { question: "Which sitcom features characters named Sheldon, Leonard, and Penny?", answer: "The Big Bang Theory", category: "Pop Culture & Movies" },

  // Sports & Games
  { question: "How many players are on the field for one team in a soccer match?", answer: "11", category: "Sports & Games" },
  { question: "Which country has won the most FIFA World Cups?", answer: "Brazil", category: "Sports & Games" },
  { question: "What is the highest score possible with a single dart in darts?", answer: "60", category: "Sports & Games" },
  { question: "Which game features terms like 'checkmate' and 'castling'?", answer: "Chess", category: "Sports & Games" },
  { question: "How many rings are there on the Olympic flag?", answer: "Five", category: "Sports & Games" },
  { question: "Who is often considered the greatest basketball player of all time, wearing jersey #23 for the Chicago Bulls?", answer: "Michael Jordan", category: "Sports & Games" },
  { question: "What color card does a referee show to eject a player in soccer?", answer: "Red", category: "Sports & Games" },
  { question: "In tennis, what word represents a score of zero?", answer: "Love", category: "Sports & Games" },
  { question: "How many pockets are there on a standard pool table?", answer: "Six", category: "Sports & Games" },
  { question: "Which golf tournament awards the winner a Green Jacket?", answer: "The Masters", category: "Sports & Games" },
  { question: "What is the diameter of a basketball hoop in inches?", answer: "18", category: "Sports & Games" },
  { question: "In which sport would you use a shuttlecock?", answer: "Badminton", category: "Sports & Games" },
  { question: "What board game involves buying property and building hotels?", answer: "Monopoly", category: "Sports & Games" },
  { question: "How many strikes in a row make a 'turkey' in bowling?", answer: "Three", category: "Sports & Games" },
  { question: "Which country is the sport of cricket most popular in, having won multiple ICC World Cups?", answer: "Australia", category: "Sports & Games" },
  { question: "How many players are on a baseball team on the field at one time?", answer: "Nine", category: "Sports & Games" },
  { question: "Which sport involves competitors throwing a discus?", answer: "Track and Field", category: "Sports & Games" },
  { question: "In Formula 1, how many points does the winner of a race typically receive?", answer: "25", category: "Sports & Games" },
  { question: "What is the name of the trophy awarded to the winner of the Wimbledon tennis tournament?", answer: "Venus Rosewater Dish", category: "Sports & Games" },
  { question: "How many sides does a dartboard have numbers on?", answer: "20", category: "Sports & Games" },

  // Additional General Knowledge
  { question: "What is the largest mammal in the world?", answer: "Blue Whale", category: "General Knowledge" },
  { question: "How many strings does a violin have?", answer: "Four", category: "General Knowledge" },
  { question: "What is the fastest land animal?", answer: "Cheetah", category: "General Knowledge" },
  { question: "How many sides does a hexagon have?", answer: "Six", category: "General Knowledge" },
  { question: "What is the smallest bone in the human body?", answer: "Stapes", category: "General Knowledge" },
  { question: "How many minutes are in a full week?", answer: "10080", category: "General Knowledge" },
  { question: "What is the most spoken language in the world by native speakers?", answer: "Mandarin Chinese", category: "General Knowledge" },
  { question: "How many strings does a standard guitar have?", answer: "Six", category: "General Knowledge" },
  { question: "What is the capital of Canada?", answer: "Ottawa", category: "General Knowledge" },
  { question: "Which animal can sleep standing up?", answer: "Horse", category: "General Knowledge" },

  // Additional Science & Tech
  { question: "What is the chemical symbol for Silver?", answer: "Ag", category: "Science & Tech" },
  { question: "How many bones are in the adult human body?", answer: "206", category: "Science & Tech" },
  { question: "What does DNA stand for?", answer: "Deoxyribonucleic Acid", category: "Science & Tech" },
  { question: "What is the boiling point of water in Celsius?", answer: "100", category: "Science & Tech" },
  { question: "Which element is represented by the symbol Fe?", answer: "Iron", category: "Science & Tech" },
  { question: "What is the study of living organisms called?", answer: "Biology", category: "Science & Tech" },
  { question: "What gas is most abundant in Earth's atmosphere?", answer: "Nitrogen", category: "Science & Tech" },
  { question: "How many chambers does a human heart have?", answer: "Four", category: "Science & Tech" },
  { question: "What is the most abundant element in the universe?", answer: "Hydrogen", category: "Science & Tech" },
  { question: "What does GPU stand for?", answer: "Graphics Processing Unit", category: "Science & Tech" },

  // Additional History & Geography
  { question: "What is the capital of Germany?", answer: "Berlin", category: "History & Geography" },
  { question: "Which year did the Titanic sink?", answer: "1912", category: "History & Geography" },
  { question: "What is the capital of India?", answer: "New Delhi", category: "History & Geography" },
  { question: "In which city was the Declaration of Independence signed?", answer: "Philadelphia", category: "History & Geography" },
  { question: "What is the capital of South Africa?", answer: "Pretoria", category: "History & Geography" },
  { question: "Which European city is built on canals?", answer: "Venice", category: "History & Geography" },
  { question: "What is the second-largest country by population in the world?", answer: "India", category: "History & Geography" },
  { question: "Which country is home to the Great Wall?", answer: "China", category: "History & Geography" },
  { question: "In which country is the Sahara Desert primarily located?", answer: "Egypt", category: "History & Geography" },
  { question: "What is the capital of Brazil?", answer: "Brasília", category: "History & Geography" },

  // Additional Pop Culture & Movies
  { question: "In which year did the Titanic movie starring Leonardo DiCaprio release?", answer: "1997", category: "Pop Culture & Movies" },
  { question: "What is the name of the main character in the James Bond franchise?", answer: "James Bond", category: "Pop Culture & Movies" },
  { question: "Who is the creator of the Marvel Universe?", answer: "Stan Lee", category: "Pop Culture & Movies" },
  { question: "What is the name of the currency used in the movie Black Panther?", answer: "Wakandan currency", category: "Pop Culture & Movies" },
  { question: "Which actor played Iron Man in the MCU?", answer: "Robert Downey Jr.", category: "Pop Culture & Movies" },
  { question: "What is the name of Elsa's snowman in Frozen?", answer: "Olaf", category: "Pop Culture & Movies" },
  { question: "Which movie features the song 'Let It Go'?", answer: "Frozen", category: "Pop Culture & Movies" },
  { question: "Who plays Captain America in the MCU?", answer: "Chris Evans", category: "Pop Culture & Movies" },
  { question: "What is the name of the princess in Cinderella?", answer: "Ella", category: "Pop Culture & Movies" },
  { question: "Which horror movie features a masked killer named Michael Myers?", answer: "Halloween", category: "Pop Culture & Movies" },

  // More General Knowledge
  { question: "What is the second-largest desert in the world?", answer: "Arctic", category: "General Knowledge" },
  { question: "How many minutes are there in 24 hours?", answer: "1440", category: "General Knowledge" },
  { question: "What is the capital of Italy?", answer: "Rome", category: "General Knowledge" },
  { question: "Which mammal is known for its ability to change color?", answer: "Chameleon", category: "General Knowledge" },
  { question: "What is the capital of South Korea?", answer: "Seoul", category: "General Knowledge" },
  { question: "How many sides does a triangle have?", answer: "Three", category: "General Knowledge" },
  { question: "What is the smallest country by area in the world?", answer: "Monaco", category: "General Knowledge" },
  { question: "Which bird is known for its ability to fly backwards?", answer: "Hummingbird", category: "General Knowledge" },
  { question: "What is the capital of Mexico?", answer: "Mexico City", category: "General Knowledge" },
  { question: "How many continents are there?", answer: "Seven", category: "General Knowledge" },
  { question: "What is the only mammal that cannot jump?", answer: "Elephant", category: "General Knowledge" },
  { question: "What is the capital of Greece?", answer: "Athens", category: "General Knowledge" },

  // More Science & Tech
  { question: "What is the chemical symbol for Copper?", answer: "Cu", category: "Science & Tech" },
  { question: "How many teeth does an adult human typically have?", answer: "32", category: "Science & Tech" },
  { question: "What is the smallest unit of life?", answer: "Cell", category: "Science & Tech" },
  { question: "Which scientist is famous for the theory of relativity?", answer: "Albert Einstein", category: "Science & Tech" },
  { question: "What is the chemical formula for salt?", answer: "NaCl", category: "Science & Tech" },
  { question: "How many chambers does a fish heart have?", answer: "Two", category: "Science & Tech" },
  { question: "What is the process by which plants make their own food?", answer: "Photosynthesis", category: "Science & Tech" },
  { question: "What is the largest internal organ in the human body?", answer: "Liver", category: "Science & Tech" },
  { question: "How many minutes does it take light from the Sun to reach Earth?", answer: "Eight", category: "Science & Tech" },
  { question: "What is the study of stars and space called?", answer: "Astronomy", category: "Science & Tech" },
  { question: "What is the chemical symbol for Potassium?", answer: "K", category: "Science & Tech" },
  { question: "How fast does the Earth orbit the Sun?", answer: "30 kilometers per second", category: "Science & Tech" },

  // More History & Geography
  { question: "What is the capital of Spain?", answer: "Madrid", category: "History & Geography" },
  { question: "Which year did World War I end?", answer: "1918", category: "History & Geography" },
  { question: "What is the capital of Thailand?", answer: "Bangkok", category: "History & Geography" },
  { question: "Which empire built the Colosseum in Rome?", answer: "Roman Empire", category: "History & Geography" },
  { question: "What is the second-longest river in the world?", answer: "Amazon", category: "History & Geography" },
  { question: "In which country is Mount Kilimanjaro located?", answer: "Tanzania", category: "History & Geography" },
  { question: "What is the capital of Egypt?", answer: "Cairo", category: "History & Geography" },
  { question: "Who was the first Emperor of China?", answer: "Qin Shi Huang", category: "History & Geography" },
  { question: "What is the deepest ocean trench in the world?", answer: "Mariana Trench", category: "History & Geography" },
  { question: "In which country is the Statue of Liberty located?", answer: "United States", category: "History & Geography" },
  { question: "What is the capital of Portugal?", answer: "Lisbon", category: "History & Geography" },
  { question: "Which desert is the largest in the world?", answer: "Antarctic", category: "History & Geography" },

  // More Pop Culture & Movies
  { question: "Who plays Spider-Man in the MCU?", answer: "Tom Holland", category: "Pop Culture & Movies" },
  { question: "What is the name of the green ogre in the movie Shrek?", answer: "Shrek", category: "Pop Culture & Movies" },
  { question: "Which movie features the character Darth Vader?", answer: "Star Wars", category: "Pop Culture & Movies" },
  { question: "Who directed the movie 'Jaws'?", answer: "Steven Spielberg", category: "Pop Culture & Movies" },
  { question: "What is the name of the main villain in The Lion King?", answer: "Scar", category: "Pop Culture & Movies" },
  { question: "Which actor plays Tony Stark in the MCU?", answer: "Robert Downey Jr.", category: "Pop Culture & Movies" },
  { question: "What is the name of the character played by Johnny Depp in Pirates of the Caribbean?", answer: "Captain Jack Sparrow", category: "Pop Culture & Movies" },
  { question: "Which movie features the song 'Hakuna Matata'?", answer: "The Lion King", category: "Pop Culture & Movies" },
  { question: "What is the name of Simba's mother in The Lion King?", answer: "Sarabi", category: "Pop Culture & Movies" },
  { question: "Who directed the movie 'The Matrix'?", answer: "Lana Wachowski and Lilly Wachowski", category: "Pop Culture & Movies" },
  { question: "What is the name of the villain in The Incredibles?", answer: "Syndrome", category: "Pop Culture & Movies" },
  { question: "Which TV series features a group of six friends living in New York?", answer: "Friends", category: "Pop Culture & Movies" },

  // More Sports & Games
  { question: "How many players are on a volleyball team on the court at one time?", answer: "Six", category: "Sports & Games" },
  { question: "Which sport uses a puck?", answer: "Hockey", category: "Sports & Games" },
  { question: "In which sport would you encounter a 'home run'?", answer: "Baseball", category: "Sports & Games" },
  { question: "How many players are on an American football team on the field at one time?", answer: "Eleven", category: "Sports & Games" },
  { question: "What is the minimum number of players needed to play basketball?", answer: "Two", category: "Sports & Games" },
  { question: "In which sport would you use a 'racket'?", answer: "Tennis", category: "Sports & Games" },
  { question: "How many holes are there on a standard golf course?", answer: "Eighteen", category: "Sports & Games" },
  { question: "Which sport uses a net and a ball with a diameter of 6.7 centimeters?", answer: "Volleyball", category: "Sports & Games" },
  { question: "What is the objective of the game 'Go'?", answer: "Control the most territory", category: "Sports & Games" },
  { question: "How many pieces does each player start with in Chess?", answer: "Sixteen", category: "Sports & Games" },
  { question: "What sport involves competitors grappling on a mat?", answer: "Wrestling", category: "Sports & Games" },
  { question: "In which sport would you encounter 'pin' and 'spare'?", answer: "Bowling", category: "Sports & Games" }
];

// Export if running in Node.js environment, otherwise define globally
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = TRIVIA_QUESTIONS;
}
